version: '2'
services:
  devtoolsproxy:
    image: nginx:1.13.8-alpine
    container_name: devtoolsproxy
    ports:
     - "80:80"
    restart: always
    volumes: 
    - ./html:/usr/share/nginx/html:ro
    #- ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
     #- /opt/svn:/opt/svn
     #- ./html:/var/www/html
     #- ./etc/apache2:/etc/apache2
     #- ./etc/perl:/etc/perl
     #- /etc/apache2/mods-enabled/dav_svn.conf:/etc/apache2/mods-enabled/dav_svn.conf
     #- /opt/svn:/opt/svn
     
