version: "2"

services:
  sonar:
    image: sonarqube:6.7.1-alpine
    container_name: sonar
    depends_on:
      - sonar_db
#    user: sonarqube
    ports:
      - "9000:9000"
    restart: always
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
    volumes:
      - ./opt/sonarqube/conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - ./opt/sonarqube/data:/opt/sonarqube/data
      - ./opt/sonarqube/extensions:/opt/sonarqube/extensions
      - ./opt/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    
#      - sonarqube_conf:/opt/sonarqube/conf
#      - sonarqube_data:/opt/sonarqube/data
#- sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonar_db:
    image: postgres:9.6.6-alpine
    container_name: sonar_db
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonar_postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - sonar_postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  #sonarqube_conf:
  #sonarqube_data:
  #sonarqube_extensions:
  #sonarqube_bundled-plugins:
  sonar_postgresql:
  sonar_postgresql_data:
