FROM sonarqube:6.7.1-alpine
MAINTAINER Andriy Potapov <andriypotapov@gmail.com>

# overwrite specific apache2 configurations
COPY ./opt/sonarqube/conf/sonar.properties /opt/sonarqube/conf/sonar.properties

